repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: 'uv.lock'
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

  # Check for secrets with gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        # Use config from pyproject.toml
        args: ["--config", "pyproject.toml"]
        # This allows the hook to pass even if the config file doesn't exist yet
        pass_filenames: false

  # AWS credentials scanner
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  # Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  # Python security check
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

  # Custom full-lint script (runs all linting checks at once)
  - repo: local
    hooks:
      - id: full-lint
        name: Full Lint
        description: Runs all linting checks (ruff, ruff-format, bandit)
        entry: scripts/full-lint.sh
        language: script
        pass_filenames: false
        types: [python]
